name: emb3rs-cf-module
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=
  - colorama=
  - numpy=
  - pandas=
  - geopy=
  - pvlib-python=
  - urllib3=
  - beautifulsoup4=
  - matplotlib=
  - requests=
  - urllib3
  - pip:
    - beautifulsoup4==4.11.1
    - geopy==2.2.0
    - mpld3==0.5.8
    - openpyxl==3.0.10
    - pvlib==0.9.1
