name: emb3rs-cf-module
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=
  - colorama=
  - numpy=
  - pandas=
  - geopy=
  - pvlib-python=
  - urllib3=
  - beautifulsoup4=
  - matplotlib=
  - requests=

